name: dashboard_grid
description: >-
  Configurable dashboard widget, which allows drag and drop
version: 0.0.6
repository: https://github.com/nonameden/dashboard_grid

topics:
  - widgets

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  melos: ^7.3.0
